sudo: false
language: ruby
cache:
  bundler: true
  directories:
  - tmp/cache/assets/test
rvm:
- 2.3.0
addons:
  postgresql: 9.4
before_script:
- "./bin/rake db:setup RAILS_ENV=test"
deploy:
  provider: heroku
  api_key:
    secure: EmgSexQs5anGHJccSSNsPWG0WSQWUrgFfLuPiE+h1UtExWyuvIxl8b0mjpXnR43DsfsIkQ9ObqSmCi7dfuUniodTxWP8d0d1u+yoKhIAVwgUOiEj5jIIK+hXiQOlVyIEIzmBIClnWXkMbx1tseCxSnXtucy85wcP8wSmj6KxA7MQxWBhkTN6rrM+rY44SQXNgyvj2Quu32DGFB9P8G8zlMdq/ywMekErv5heXTCl79z12B0mfVc6ShLryKkcrt39aSbC29YlEpOCBdhimt4Vjn9phwI9I553hQ+GIJxWSTgfVko62WPRN0LPbqH8l+vzSySNOTV46oSz+djy5AdJeyYl9kH1ATb1A66GgSwEk+TlpfGFNrgcaZgJjoNe3ay/zqqoyB5U4lQBDAE89ekAOpElVtOaOWmRF6VscLrsmehh9rwu8TjQdHZjaUwfcYaZViN7iqqfupOyvac8S9JQF6sBEzP1aq/u416fXxudLgh5tYCq9/lE1xA6rD0Enc89wD0fdXd97V1X1lFPR8HHu2piMP4K3nlLZQCw7/botu8dMRZyoJolfqloljgoomQ9acJXMnSItUXIpnBNfQrvHFBkfSFWpS+09rR1PDXh0Urwd8mAmKQyO8eIVWKgqjWi4yYxbDhdX/SVKDEpjtGDside+5SUjG2uXrKShszQwWk=
  app: staging-data-pensionwise
  on:
    repo: guidance-guarantee-programme/data
  run: "./bin/rake db:migrate"
notifications:
  slack:
    secure: hO+nTHFRBzxqhPuwS+48hof6tOb58yRmtRZYeKKSp4ihU2TiPV+mYlcSoEXD2yBEceQ5gKu5TxAEwtHlC5hPkdIweszwExRYg2lWHxafe0/Tlf5E/l61Tm/kLjl94A73AI0Imbz3gXVfm++x9YMhQxjRB8a9rNOUlcgd4ZQHtjdN1CqKE3SZRTTFUd84n5kXfuq+hvupweL9VJXtucTXwGkv3RmsSE2Snl70aKU3Tfd++tesY+nrX2ZCWMvpHSaj1y/l26owtS1FPRIBEdrBlqGE1k4VUBoJbMdZ+n/8GJrqp7C/mn7jj//1LfYFxpz7ncftuFk7WIgUL8s4z2dF69ZArujUpJak9amMuTiVwvfXKQkGOv+QLwEIwrTcU55QAt39CWlI35D9v+FSqrwSLSbefsG57EqT233fhWC61vwek/c8JvhkU+BAeHEQ4o9Ik43WJ9bgqH3dpGppU3nEP7ccZB2oHDkUAmRXaayCZrzxLXzIwe2GcizrAHLyUgdXFBr6+C/dvG85KKEiCxcEP9Pb1qE7kIM1v+6xNaW9IZN22svFeRKmYqKuJbnVlt8S4/VuMKHF79xoaEr7NnkYD/32wzBN2YPjzLIlKxEmREW9gX34HtjcvH0xbFeIVst60p5gmovD+6IEOTrpPNNmtYeD0Z7v88riiBdb7Ej5HIQ=
