sudo: false
language: ruby
cache:
  bundler: true
  directories:
  - tmp/cache/assets/test
rvm:
- 2.3.0
addons:
  postgresql: 9.4
before_script:
- "./bin/rake db:setup RAILS_ENV=test"
deploy:
  provider: heroku
  api_key:
    secure: HiF9NM9MD0r1mryVn3bdUJis8MWY0795q908x1kT4Vo4nuM/KQX7jh5QYtb+3hUGkHfKlrrMOTaqVWKVg5utDB2WtfP4/nOWF14co6TYqxFZwshs3tFWlrgWj+2nArhwt4UYCkGNY3QD6LLP4cNzaE0SEAUyj6TgGV+rLoGVz8NTe7d53fQNdnV72rZi/m2VY1123YWkQtxvbF0GJtiotD/xS0yeqwC4zRok5RKD7vEfm8Tthbj8Jaiuxd7atGhIvvRsgxTTZ1BjOngc+6HgxdT8Bdxtc2wM/aXbjH7kJWPcOXLOoA6IcpUeeN3gK6K1vwtA9CDOlXkWRtNViCzOwkTT6HsDRkzF0TVvLWBaBQsHnHY5+305N1XKokRjuS6d8YVQ97F1OWvPx1aAvLKUHaQ1lTf1LXzmFRGeCSogdMwmJ0O2Z5PspYq0HGklTymYFek5OdBkZJUF0VsNIof5Sy2WLgJSNEePRfNYF30cMf2jdqTCfJYrN3VdVSf5iwKGSeiQC+Tu7l5RWxVMZQ+1Nm7yYDh6hMsxnUpjZNO5BlhAnXtfa4Y92iDLxS6KoFK8/LA+IbSMfo/Cp65VlrFmtJGKMDmh9BkIC0PC65hbE+vOXgEbe3jx2rwlNaXUjpPtMXKdxlEClXhXiZiEJTSOeHTKAZ7PiDpZdo0G+EsyM+Y=
  app: staging-data-pensionwise
  on:
    repo: guidance-guarantee-programme/data
  run: "./bin/rake db:migrate"
notifications:
  slack:
    secure: dbkW7tikYd7n+K8JgMmfowamyeYxWAFkEEJbtVwKtKaucxezrrfggdThKnrQSu5a9JDwl3Owfy8Cd8XICG/Sy92REM9i6MIMeiO95j4lHwVt4up9UvXrxWbcHczRcBFFNAPj0oxRNFYmkwyYVq
